{
  "error_type": "RuntimeError",
  "message": "Traceback (most recent call last):\n  File \"/home/wan00559/cuda_mind_evolution/scripts/compile_and_run.py\", line 218, in compare_and_bench\n    raise ValueError(f\"max_abs_err={max_err:.3e} > tol={tol}\")\nValueError: max_abs_err=1.535e+02 > tol=0.0001\n"
}